import type { Metadata } from "next"
import { Cabin } from "next/font/google"
import type { ReactNode } from "react"
import "./globals.css"

export const metadata: Metadata = {
	title: "Arcadia",
	description: "Generated by create next app",
}

const font = Cabin({
	subsets: ["latin"],
})

interface RootLayoutProps {
	children: ReactNode
}

export default function RootLayout(props: RootLayoutProps) {
	return (
		<html lang="en">
			<body className={`${font.className} antialiased`}>{props.children}</body>
		</html>
	)
}
